name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Build the dynamic module
      run: |
        make
    - name: Byte compile
      run: |
        emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile *.el
    - name: Run tests
      run: |
        emacs -Q --batch -L . -l *-tests.el -f ert-run-tests-batch-and-exit
